apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../stable
namespace:
  gce-pd-csi-driver
images:
# Replace this with your private image names and tags
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/dyzz-csi-staging/csi/gce-pd-driver
  newTag: "latest"
